version: "3"
services:
  web:
    image: training/webapp
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    depends_on:
      - redis
    networks:
      - backend
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - backend
  redis:
    image: redis
    networks:
      - backend
  nginx:
    image: nginx
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == manager]
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ../nginx/files/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend
networks:
  backend: