---
- name: Create swarm worker
  command: docker swarm join --advertise-addr {{ ip }} --listen-addr {{ ip }}:2377 --token {{ hostvars['manager-1']['swarm_token']['stdout'] }} {{ swarm_leader_ip }}:2377
  when: swarm_leader_ip is defined
  ignore_errors: True
  tags: [swarm_worker]