version: "3"
services:
  nginx:
    image: nginx
    deploy:
      replicas: 2
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./files/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - frontend
networks:
  frontend: